site_name: UI Requirement Document

nav:
  - UI Framework需求: 
      - '布局 Layout': 'index.md'
      - '字体 Typography': 'typography.md'
      - '颜色 Color': 'color.md'
      - '图标 Icon': 'icon.md'
      - '按钮 Button': 'button.md'
      - '选择器 Selection': 'selection.md'


theme:
  name: material
  features:
    tabs: true