# Create by HW on Oct 16 2020.
# Copyright © NS Produt Team. All right reserved.

site_name: NS 产品文档

nav:
  - Home: index.md
  - UI Framework 需求:
      - 首页 Home: ns_ui_framework/home.md
      - 特点 Feature:
        - 整体说明 General: ns_ui_framework/features/general.md
        - 布局 Layout: ns_ui_framework/features/layout.md
      - 风格 Style:
        - 字体 Typography: ns_ui_framework/style/typography.md
        - 颜色 Color: ns_ui_framework/style/color.md
      - 组件 Component:
        - 图标 Icon: ns_ui_framework/component/icon.md
        - 按钮 Button: 
          - 按钮 Button: ns_ui_framework/component/button/button.md
          - 图标按钮 Icon Button: ns_ui_framework/component/button/icon_button.md
        - 选择器 Selection:
          - 多选 Checkbox: ns_ui_framework/component/selection/checkbox.md
          - 单选 Radio: ns_ui_framework/component/selection/radio.md
          - 按钮栏 Button Bar: ns_ui_framework/component/selection/button_bar.md
          - 图标按钮栏 Icon Button Bar: ns_ui_framework/component/selection/icon_button_bar.md
          - 菜单栏 Menu Bar: ns_ui_framework/component/selection/menu_bar.md
          - 开关 Switch: ns_ui_framework/component/selection/switch.md
          - 纸片 Chip: ns_ui_framework/component/selection/chip.md
          - 扩展纸片 Expandable Chip: ns_ui_framework/component/selection/expandable_chip.md
          - 下拉菜单 Dropdown: ns_ui_framework/component/selection/dropdown.md
        - 反馈 Feedback: 
          - 工具提示 Tooltip: ns_ui_framework/component/feedback/tooltip.md
          - 对话框 Dialog: ns_ui_framework/component/feedback/dialog.md
          - 加载 Loading: ns_ui_framework/component/feedback/loading.md
          - 通知 Notification: ns_ui_framework/component/feedback/notification.md
          - 提醒 Alert: ns_ui_framework/component/feedback/alert.md
        - 容器 Container:
          - 卡片 Card: ns_ui_framework/component/container/card.md
          - 扩展面板 Accordion: ns_ui_framework/component/container/accordion.md
        - 数据 Data:
          - 数据表 Data Table: ns_ui_framework/component/data/data_table.md
      - 交互说明:
        - Interactive Instructions: ns_ui_framework/interactive_instructions.md
  - NavInfo Simulation 需求:
      - 仿真任务 Simulation Task: 
        - 任务 (卡片功能): ns_prd/task/endurance_test_card.md
        - 查看任务详情:
          - Scenario Test: ns_prd/task_detail/scenario_test_monitor.md
          - Endurance Test: 
            - Endurance Test Monitor: ns_prd/task_detail/endurance_test_monitor.md
            - Endurance Test Monitor - Traffic Flow Configure: ns_prd/task_detail/endurance_test_monitor_traffic_flow_configure.md
      -  仿真平台使用手册 NS User Guide: ns_prd/user_guide/user_guide.md
  - Produt Team:
    - Plan (UI Framework): product_team/plan_ui_framework/plan_ui_framework.md
    - Weekly Report:
      - 吕涵: 
        - 周报列表: product_team/weekly_report/lvhan/index.md
        - 2020-10: product_team/weekly_report/lvhan/lh_2020-10.md
      - 田子竹: 
        - 周报列表: product_team/weekly_report/tianzizhu/index.md
        - 2020-11: product_team/weekly_report/tianzizhu/tzz_2020-11.md
        - 2020-10: product_team/weekly_report/tianzizhu/tzz_2020-10.md
      - 王涵: 
        - 周报列表: product_team/weekly_report/wanghan/index.md
    - Resources:
      - Sketch: product_team/resource/sketch/resource_sketch.md
      - Issue: product_team/resource/issue/resource_issue.md
  - AWS 调研:
    - AWS 计费与结算方式: aws/aws_pricing.md
  - Ansys 调研: 
    - Ansys 自动驾驶技术: ansys/ansys_autonomy.md
    - Ansys 自动驾驶平台: ansys/ansys_construction.md

theme:
  name: material
  language: en
  font: false
  features:
    - tabs

markdown_extensions:
  - admonition: # 提示块
  - footnotes: # 脚注
  - pymdownx.critic: # 高亮
  - pymdownx.details: # 抽屉效果提示块
  - pymdownx.tabbed: # Tab效果

copyright: Copyright &copy; 2020 NS Produt Team