site_name: UI Requirement Document

nav:
  - UI Framework需求: 
      - '页面需求': 'index.md'
      - '字体需求': 'typography.md'
      - '颜色需求': 'color.md'


theme:
  name: material
  features:
    tabs: true